version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    tty: true
    networks:
      app_subnet:
        ipv4_address: 172.16.1.4
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db_p1'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      app_subnet:
        ipv4_address: 172.16.1.3
# Names our volume
volumes:
  my-db:

networks:
  app_subnet:
    external: true